islandora_xacml_editor.settings:
  type: config_object
  label: Settings
  mapping:
    islandora_xacml_editor_restricted_dsids:
      type: string
    islandora_xacml_editor_restricted_mimes:
      type: string
    islandora_xacml_editor_show_dsidregex:
      type: integer
    islandora_xacml_editor_show_mimeregex:
      type: integer
    islandora_xacml_editor_default_users:
      type: sequence
    islandora_xacml_editor_default_roles:
      type: sequence
