islandora_xacml_api.settings:
  type: config_object
  label: Settings
  mapping:
    islandora_xacml_api_save_relationships:
      type: boolean
    islandora_xacml_api_rels_viewable_role:
      type: string
    islandora_xacml_api_rels_viewable_user:
      type: string
